/**
 * lib/comparateur.ts — données statiques de tous les comparateurs produit.
 * amazonUrl: '' = lien à venir (fourni par l'utilisateur).
 * Toujours passer amazonUrl via AffiliateLink / addAffiliateTag().
 */

export type ModeleComparateur = {
  nom: string
  prix: number
  nouveaute?: boolean
  amazonUrl: string  // '' = à venir
  specs: Record<string, string>
}

export type ProduitComparateur = {
  id: string
  label: string
  description: string
  specsLabels: Record<string, string>
  modeles: ModeleComparateur[]
}

export const COMPARATEURS: Record<string, ProduitComparateur> = {
  iphone: {
    id: 'iphone',
    label: 'iPhone',
    description: 'Compare tous les iPhone côte à côte : puce, caméra, écran, autonomie et prix.',
    specsLabels: {
      puce: 'Puce',
      ecran: 'Écran',
      photo: 'Photo principale',
      batterie: 'Autonomie vidéo',
      stockage: 'Stockage min.',
    },
    modeles: [
      {
        nom: 'iPhone 17e',
        prix: 799,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0GQWCGCJ1',
        specs: {
          puce: 'A18',
          ecran: '6,1\" OLED 60Hz',
          photo: '48 MP Fusion',
          batterie: '22h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 17 Air',
        prix: 899,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/Apple-iPhone-Air-256-Puissante/dp/B0FQH6GMDX',
        specs: {
          puce: 'A18',
          ecran: '6,6\" OLED Super Retina XDR',
          photo: '48 MP Fusion',
          batterie: '20h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 17',
        prix: 999,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/Apple-iPhone-17-256GB-black/dp/B0FQFJVJBQ',
        specs: {
          puce: 'A19',
          ecran: '6,3\" OLED 120Hz ProMotion',
          photo: '48 MP Fusion + 12 MP ultra-grand-angle',
          batterie: '24h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 17 Pro',
        prix: 1229,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/Apple-iPhone-Pro-256-prodigieuse/dp/B0FQH32F7H',
        specs: {
          puce: 'A19 Pro',
          ecran: '6,3\" OLED 120Hz ProMotion',
          photo: '48 MP Fusion + 48 MP ultra-grand-angle + 12 MP téléobjectif 5×',
          batterie: '27h',
          stockage: '256 Go',
        },
      },
      {
        nom: 'iPhone 17 Pro Max',
        prix: 1479,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/Apple-iPhone-Pro-Max-256/dp/B0FQH9R2VG',
        specs: {
          puce: 'A19 Pro',
          ecran: '6,9\" OLED 120Hz ProMotion',
          photo: '48 MP Fusion + 48 MP ultra-grand-angle + 12 MP téléobjectif 5×',
          batterie: '37h',
          stockage: '256 Go',
        },
      },
      {
        nom: 'iPhone 16e',
        prix: 699,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DXQQ65T2',
        specs: {
          puce: 'A16 Bionic',
          ecran: '6,1\" OLED 60Hz',
          photo: '48 MP Fusion',
          batterie: '26h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 16',
        prix: 769,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DGHN3YNR',
        specs: {
          puce: 'A18',
          ecran: '6,1\" OLED 60Hz',
          photo: '48 MP Fusion + 12 MP Ultra',
          batterie: '22h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 16 Plus',
        prix: 869,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DGHQW185',
        specs: {
          puce: 'A18',
          ecran: '6,7\" OLED 60Hz',
          photo: '48 MP Fusion + 12 MP Ultra',
          batterie: '27h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 16 Pro',
        prix: 1029,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DGHH9JY3',
        specs: {
          puce: 'A18 Pro',
          ecran: '6,3\" ProMotion 120Hz',
          photo: '48+12+12 MP ProRAW',
          batterie: '27h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 16 Pro Max',
        prix: 1279,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DGHYHG25',
        specs: {
          puce: 'A18 Pro',
          ecran: '6,9\" ProMotion 120Hz',
          photo: '48+12+12 MP ProRAW',
          batterie: '33h',
          stockage: '256 Go',
        },
      },
      {
        nom: 'iPhone 15',
        prix: 669,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0CHX7Z69Z',
        specs: {
          puce: 'A16 Bionic',
          ecran: '6,1\" OLED 60Hz',
          photo: '48 MP Fusion',
          batterie: '20h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 15 Plus',
        prix: 769,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0CHX2DRNW',
        specs: {
          puce: 'A16 Bionic',
          ecran: '6,7\" OLED 60Hz',
          photo: '48 MP Fusion',
          batterie: '26h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 15 Pro',
        prix: 969,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0CHX53QY9',
        specs: {
          puce: 'A17 Pro',
          ecran: '6,1\" ProMotion 120Hz',
          photo: '48+12+12 MP ProRAW',
          batterie: '23h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 15 Pro Max',
        prix: 1129,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0CHWYY97M',
        specs: {
          puce: 'A17 Pro',
          ecran: '6,7\" ProMotion 120Hz',
          photo: '48+12+12 MP ProRAW · 5× zoom',
          batterie: '29h',
          stockage: '256 Go',
        },
      },
      {
        nom: 'iPhone 14',
        prix: 629,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0BDJC83QY',
        specs: {
          puce: 'A15 Bionic',
          ecran: '6,1\" OLED 60Hz',
          photo: '12+12 MP',
          batterie: '20h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 14 Plus',
        prix: 729,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0BDHR3MHB',
        specs: {
          puce: 'A15 Bionic',
          ecran: '6,7\" OLED 60Hz',
          photo: '12+12 MP',
          batterie: '26h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 14 Pro',
        prix: 799,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0BDJB4WBK',
        specs: {
          puce: 'A16 Bionic',
          ecran: '6,1\" ProMotion 120Hz',
          photo: '48+12+12 MP ProRAW',
          batterie: '23h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 14 Pro Max',
        prix: 999,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0BDHZH6R6',
        specs: {
          puce: 'A16 Bionic',
          ecran: '6,7\" ProMotion 120Hz',
          photo: '48+12+12 MP ProRAW',
          batterie: '29h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 13',
        prix: 499,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B09V3KN99J',
        specs: {
          puce: 'A15 Bionic',
          ecran: '6,1\" OLED 60Hz',
          photo: '12+12 MP',
          batterie: '19h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 13 mini',
        prix: 449,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B09V3J7TCF',
        specs: {
          puce: 'A15 Bionic',
          ecran: '5,4\" OLED 60Hz',
          photo: '12+12 MP',
          batterie: '17h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 13 Pro',
        prix: 699,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B09V3KZQ86',
        specs: {
          puce: 'A15 Bionic',
          ecran: '6,1\" ProMotion 120Hz',
          photo: '12+12+12 MP ProRAW',
          batterie: '22h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 13 Pro Max',
        prix: 799,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B09V4418SZ',
        specs: {
          puce: 'A15 Bionic',
          ecran: '6,7\" ProMotion 120Hz',
          photo: '12+12+12 MP ProRAW',
          batterie: '28h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 12',
        prix: 349,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B08L5T599Y',
        specs: {
          puce: 'A14 Bionic',
          ecran: '6,1\" OLED 60Hz',
          photo: '12+12 MP',
          batterie: '17h',
          stockage: '64 Go',
        },
      },
      {
        nom: 'iPhone 12 mini',
        prix: 299,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B08L5SXYY5',
        specs: {
          puce: 'A14 Bionic',
          ecran: '5,4\" OLED 60Hz',
          photo: '12+12 MP',
          batterie: '15h',
          stockage: '64 Go',
        },
      },
      {
        nom: 'iPhone 12 Pro',
        prix: 499,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B08L5XHHF6',
        specs: {
          puce: 'A14 Bionic',
          ecran: '6,1\" OLED 60Hz ProMotion',
          photo: '12+12+12 MP ProRAW',
          batterie: '17h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 12 Pro Max',
        prix: 549,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B08L5W86Y3',
        specs: {
          puce: 'A14 Bionic',
          ecran: '6,7\" OLED 60Hz',
          photo: '12+12+12 MP ProRAW',
          batterie: '20h',
          stockage: '128 Go',
        },
      },
      {
        nom: 'iPhone 11',
        prix: 299,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B08L6WXS9W',
        specs: {
          puce: 'A13 Bionic',
          ecran: '6,1\" LCD',
          photo: '12+12 MP',
          batterie: '17h',
          stockage: '64 Go',
        },
      },
      {
        nom: 'iPhone 11 Pro',
        prix: 399,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B07XRRNYWK',
        specs: {
          puce: 'A13 Bionic',
          ecran: '5,8\" OLED 60Hz',
          photo: '12+12+12 MP',
          batterie: '18h',
          stockage: '64 Go',
        },
      },
      {
        nom: 'iPhone XR',
        prix: 249,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B08L6Z7L9Y',
        specs: {
          puce: 'A12 Bionic',
          ecran: '6,1\" LCD',
          photo: '12 MP',
          batterie: '16h',
          stockage: '64 Go',
        },
      },
      {
        nom: 'iPhone SE (2022)',
        prix: 529,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B09V492SGL',
        specs: {
          puce: 'A15 Bionic',
          ecran: '4,7\" LCD',
          photo: '12 MP',
          batterie: '15h',
          stockage: '64 Go',
        },
      },
      {
        nom: 'iPhone SE (2020)',
        prix: 199,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B08L6Z86MZ',
        specs: {
          puce: 'A13 Bionic',
          ecran: '4,7\" LCD',
          photo: '12 MP',
          batterie: '13h',
          stockage: '64 Go',
        },
      },
    ],
  },

  mac: {
    id: 'mac',
    label: 'Mac',
    description: 'MacBook Air, MacBook Pro, Mac mini, iMac — tous les Mac comparés par prix et performance.',
    specsLabels: {
      puce: 'Puce',
      ram: 'RAM',
      stockage: 'Stockage min.',
      ecran: 'Écran',
      autonomie: 'Autonomie',
      poids: 'Poids',
    },
    modeles: [
      {
        nom: 'MacBook Neo 13\"',
        prix: 699,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/Apple-MacBook-2026-Portable-avec/dp/B0GR6MBRPB',
        specs: {
          puce: 'A18 Pro',
          ram: '8 Go',
          stockage: '256 Go',
          ecran: '13\" Liquid Retina',
          autonomie: '16h',
          poids: '1,23 kg',
        },
      },
      {
        nom: 'Mac mini M4',
        prix: 699,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0DLBW9GNQ',
        specs: {
          puce: 'M4',
          ram: '16 Go',
          stockage: '256 Go',
          ecran: 'Externe requis',
          autonomie: '—',
          poids: '0,67 kg',
        },
      },
      {
        nom: 'Mac mini M4 Pro',
        prix: 1649,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0DLC5TBJ7',
        specs: {
          puce: 'M4 Pro',
          ram: '24 Go',
          stockage: '512 Go',
          ecran: 'Externe requis',
          autonomie: '—',
          poids: '0,73 kg',
        },
      },
      {
        nom: 'MacBook Air 13\" M5',
        prix: 1299,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0GR1W24CR',
        specs: {
          puce: 'M5',
          ram: '16 Go',
          stockage: '256 Go',
          ecran: '13,6\" Liquid Retina',
          autonomie: '18h',
          poids: '1,24 kg',
        },
      },
      {
        nom: 'MacBook Air 15\" M5',
        prix: 1599,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0GR1NRFZD',
        specs: {
          puce: 'M5',
          ram: '16 Go',
          stockage: '256 Go',
          ecran: '15,3\" Liquid Retina',
          autonomie: '18h',
          poids: '1,51 kg',
        },
      },
      {
        nom: 'iMac 24\" M4',
        prix: 1699,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0DL6KQ5SP',
        specs: {
          puce: 'M4',
          ram: '16 Go',
          stockage: '256 Go',
          ecran: '24\" 4,5K Retina',
          autonomie: '—',
          poids: '4,46 kg',
        },
      },
      {
        nom: 'MacBook Pro 14\" M5',
        prix: 1999,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0FWDCNPPZ',
        specs: {
          puce: 'M5',
          ram: '16 Go',
          stockage: '512 Go',
          ecran: '14,2\" Liquid Retina XDR',
          autonomie: '24h',
          poids: '1,61 kg',
        },
      },
      {
        nom: 'MacBook Pro 14\" M5 Pro',
        prix: 2499,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0FWD5WN5T',
        specs: {
          puce: 'M5 Pro',
          ram: '24 Go',
          stockage: '512 Go',
          ecran: '14,2\" Liquid Retina XDR',
          autonomie: '24h',
          poids: '1,62 kg',
        },
      },
      {
        nom: 'MacBook Pro 14\" M5 Max',
        prix: 3999,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0FWD7DWVX',
        specs: {
          puce: 'M5 Max',
          ram: '36 Go',
          stockage: '1 To',
          ecran: '14,2\" Liquid Retina XDR',
          autonomie: '22h',
          poids: '1,64 kg',
        },
      },
      {
        nom: 'MacBook Pro 16\" M5 Pro',
        prix: 2999,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0FWD6VS8M',
        specs: {
          puce: 'M5 Pro',
          ram: '24 Go',
          stockage: '512 Go',
          ecran: '16,2\" Liquid Retina XDR',
          autonomie: '24h',
          poids: '2,14 kg',
        },
      },
      {
        nom: 'MacBook Pro 16\" M5 Max',
        prix: 4499,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0FWD4V1M2',
        specs: {
          puce: 'M5 Max',
          ram: '36 Go',
          stockage: '1 To',
          ecran: '16,2\" Liquid Retina XDR',
          autonomie: '22h',
          poids: '2,16 kg',
        },
      },
      {
        nom: 'Mac Studio M4 Max',
        prix: 2399,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0DLC4SN2G',
        specs: {
          puce: 'M4 Max',
          ram: '36 Go',
          stockage: '512 Go',
          ecran: 'Externe requis',
          autonomie: '—',
          poids: '2,7 kg',
        },
      },
      {
        nom: 'Mac Studio M4 Ultra',
        prix: 4999,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0DLC5FWXR',
        specs: {
          puce: 'M4 Ultra',
          ram: '64 Go',
          stockage: '1 To',
          ecran: 'Externe requis',
          autonomie: '—',
          poids: '3,6 kg',
        },
      },
      {
        nom: 'Mac Pro M2 Ultra',
        prix: 7999,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0D5FVKJ7R',
        specs: {
          puce: 'M2 Ultra',
          ram: '64 Go',
          stockage: '1 To',
          ecran: 'Externe requis',
          autonomie: '—',
          poids: '16,9 kg',
        },
      },
    ],
  },

  ipad: {
    id: 'ipad',
    label: 'iPad',
    description: 'iPad, iPad mini, iPad Air, iPad Pro — le bon iPad selon ton usage et ton budget.',
    specsLabels: {
      puce: 'Puce',
      ecran: 'Écran',
      stockage: 'Stockage min.',
      stylet: 'Apple Pencil',
      connectique: 'Connectique',
      poids: 'Poids (Wi-Fi)',
    },
    modeles: [
      {
        nom: 'iPad 10e génération',
        prix: 409,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0BJLGVG6R',
        specs: {
          puce: 'A14 Bionic',
          ecran: '10,9\" Liquid Retina',
          stockage: '64 Go',
          stylet: 'Apple Pencil 1 (USB-C)',
          connectique: 'USB-C',
          poids: '477 g',
        },
      },
      {
        nom: 'iPad 11e génération',
        prix: 369,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0DZ75RKZH',
        specs: {
          puce: 'A16',
          ecran: '10,9\" Liquid Retina',
          stockage: '128 Go',
          stylet: 'Apple Pencil 1 (USB-C)',
          connectique: 'USB-C',
          poids: '477 g',
        },
      },
      {
        nom: 'iPad mini 7',
        prix: 599,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0DK3YHKBB',
        specs: {
          puce: 'A17 Pro',
          ecran: '8,3\" Liquid Retina',
          stockage: '128 Go',
          stylet: 'Apple Pencil Pro',
          connectique: 'USB-C',
          poids: '293 g',
        },
      },
      {
        nom: 'iPad Air 11\" M3',
        prix: 799,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0GQVLW917',
        specs: {
          puce: 'M3',
          ecran: '11\" Liquid Retina',
          stockage: '128 Go',
          stylet: 'Apple Pencil Pro',
          connectique: 'USB-C',
          poids: '462 g',
        },
      },
      {
        nom: 'iPad Air 13\" M3',
        prix: 1099,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0GQVQT9X4',
        specs: {
          puce: 'M3',
          ecran: '13\" Liquid Retina',
          stockage: '128 Go',
          stylet: 'Apple Pencil Pro',
          connectique: 'USB-C',
          poids: '617 g',
        },
      },
      {
        nom: 'iPad Pro 11\" M5',
        prix: 1199,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0FWD6KNY8',
        specs: {
          puce: 'M5',
          ecran: '11\" Ultra Retina XDR OLED',
          stockage: '256 Go',
          stylet: 'Apple Pencil Pro',
          connectique: 'Thunderbolt / USB 4',
          poids: '444 g',
        },
      },
      {
        nom: 'iPad Pro 13\" M5',
        prix: 1599,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0FWD971MY',
        specs: {
          puce: 'M5',
          ecran: '13\" Ultra Retina XDR OLED',
          stockage: '256 Go',
          stylet: 'Apple Pencil Pro',
          connectique: 'Thunderbolt / USB 4',
          poids: '579 g',
        },
      },
    ],
  },

  watch: {
    id: 'watch',
    label: 'Apple Watch',
    description: 'Watch SE, Series 10, Series 11, Ultra 2 — le bon modèle selon ton budget et ton usage sport.',
    specsLabels: {
      ecran: 'Écran',
      autonomie: 'Autonomie',
      waterproof: 'Résistance à l\'eau',
      sante: 'Santé',
      specifique: 'Spécificité',
    },
    modeles: [
      {
        nom: 'Apple Watch SE 2',
        prix: 279,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DGHZ15PD',
        specs: {
          ecran: '40 / 44 mm LTPO OLED',
          autonomie: '18h',
          waterproof: '50 m',
          sante: 'Cardio · chute · crash',
          specifique: 'Pas d\'always-on',
        },
      },
      {
        nom: 'Apple Watch Series 10',
        prix: 449,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DGHNY1K5',
        specs: {
          ecran: '42 / 46 mm Always-On',
          autonomie: '18h (36h mode éco)',
          waterproof: 'Plongée 100 m',
          sante: 'Cardio · ECG · SpO2 · apnée',
          specifique: 'La plus fine jamais produite',
        },
      },
      {
        nom: 'Apple Watch Series 11',
        prix: 449,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0FQGHR6SY',
        specs: {
          ecran: '42 / 46 mm Always-On',
          autonomie: '18h (36h mode éco)',
          waterproof: 'Plongée 100 m',
          sante: 'Cardio · ECG · SpO2 · apnée · skin sensing',
          specifique: 'Capteurs santé de nouvelle génération',
        },
      },
      {
        nom: 'Apple Watch Ultra 2',
        prix: 899,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DGJ9M892',
        specs: {
          ecran: '49 mm Always-On Micro-LED',
          autonomie: '60h (36h course)',
          waterproof: 'Plongée 100 m + EN 13319',
          sante: 'Cardio · ECG · SpO2 · température',
          specifique: 'GPS de précision double fréquence',
        },
      },
    ],
  },

  airpods: {
    id: 'airpods',
    label: 'AirPods',
    description: 'AirPods 4, AirPods Pro 2, AirPods Max — les bons écouteurs Apple selon ton usage.',
    specsLabels: {
      anc: 'Réduction de bruit',
      autonomie: 'Autonomie (ANC actif)',
      etanche: 'Résistance',
      spatial: 'Spatial Audio',
      format: 'Format',
    },
    modeles: [
      {
        nom: 'AirPods 3',
        prix: 179,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0BDHB9Y8H',
        specs: {
          anc: 'Non',
          autonomie: '6h (30h boîtier)',
          etanche: 'IPX4',
          spatial: 'Oui (head tracking)',
          format: 'Intra sans embout',
        },
      },
      {
        nom: 'AirPods 4',
        prix: 149,
        nouveaute: true,
        amazonUrl: 'https://amzn.to/4c4vSyD',
        specs: {
          anc: 'Non',
          autonomie: '5h (30h boîtier)',
          etanche: 'IPX4',
          spatial: 'Oui (head tracking)',
          format: 'Intra sans embout',
        },
      },
      {
        nom: 'AirPods 4 ANC',
        prix: 179,
        nouveaute: true,
        amazonUrl: 'https://www.amazon.fr/dp/B0FQF32239',
        specs: {
          anc: 'Oui (actif)',
          autonomie: '4h (24h boîtier)',
          etanche: 'IPX4',
          spatial: 'Oui (head tracking)',
          format: 'Intra sans embout',
        },
      },
      {
        nom: 'AirPods Pro 2',
        prix: 249,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DGHWD7CT',
        specs: {
          anc: 'Oui — meilleur ANC Apple',
          autonomie: '5,5h (30h boîtier)',
          etanche: 'IP54',
          spatial: 'Oui (Personalized)',
          format: 'Intra avec embouts',
        },
      },
      {
        nom: 'AirPods Max USB-C',
        prix: 529,
        nouveaute: false,
        amazonUrl: 'https://www.amazon.fr/dp/B0DGHQ1KVY',
        specs: {
          anc: 'Oui — référence ANC circumaural',
          autonomie: '20h',
          etanche: 'Non',
          spatial: 'Oui (Personalized)',
          format: 'Circumaural (over-ear)',
        },
      },
      {
        nom: 'AirPods Max 2',
        prix: 579,
        nouveaute: true,
        amazonUrl: '',
        specs: {
          anc: 'Oui — ANC 1,5× meilleure (puce H2)',
          autonomie: '20h',
          etanche: 'Non',
          spatial: 'Oui (Personalized + Adaptive Audio)',
          format: 'Circumaural (over-ear)',
        },
      },
    ],
  },
}

export const PRODUIT_SLUGS = Object.keys(COMPARATEURS)

export function getProduit(slug: string): ProduitComparateur | undefined {
  return COMPARATEURS[slug]
}
